### ISSUE TITLE
optional DNS service

### ISSUE THREAD

**Issue by zolug** [networkservicemesh/cmd-nsc#474]
We have some (security) concerns related to the DNS service introduced as part of NSM v1.5:
- The DNS service in NSC deliberately overwrites POD DNS config by modifying /etc/resolv.conf. Thus might interfere with other containers sharing the same POD.
- Creating a local DNS server on port 53 normally requires privileges (CAP_NET_BIND_SERVICE) if run as non-root user.
  Env variable NSM_LOCALDNSSERVERADDRESS allows configuring the port along with the IP address. But a custom port other than 53 will break DNS resolution. (Probably some DNAT rule could help in such cases, but that would require privileges as well...)
- Editing /etc/resolv.conf conflicts with our generic requirement to use read-only root file system.

We also do not rely on the functionality the integrated NSM DNS service provides. Considering these points, would be it possible to make the DNS service optional for NSC (via env var for example)?

**Comment by denis-tingaikin** [comment]
I feel this may be resolved by https://github.com/networkservicemesh/cmd-nsc/pull/473

Could you check?

**Comment by zolug** [comment]
@denis-tingaikin I gave it a try and seemed to work perfectly. Thanks a lot!

**Comment by denis-tingaikin** [comment]
@zolug You're welcome! Feel free to report any issues/questions

@NikitaSkrynnik Well done!
